"""Certificate generation using Jinja2."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from typing import List

from jinja2 import Template

from .schema import ProvenanceRecord

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Model Provenance Certificate — {{ record.model_id }}</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
  h1 { border-bottom: 3px solid #333; padding-bottom: 10px; }
  .section { margin: 20px 0; padding: 15px; background: #f8f9fa; border-radius: 8px; }
  .section h2 { margin-top: 0; color: #555; font-size: 1.1em; }
  .field { display: flex; margin: 5px 0; }
  .field .label { font-weight: bold; min-width: 180px; color: #333; }
  .field .value { color: #555; word-break: break-all; }
  .chain { border-left: 3px solid #007bff; padding-left: 15px; }
  .chain-item { margin: 10px 0; padding: 8px; background: #e9ecef; border-radius: 4px; }
  .hash { font-family: monospace; font-size: 0.85em; color: #666; }
  .verified { color: #28a745; font-weight: bold; }
  .unverified { color: #dc3545; font-weight: bold; }
  footer { margin-top: 40px; font-size: 0.85em; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head>
<body>
<h1>🔗 Model Provenance Certificate</h1>

<div class="section">
  <h2>Model Identity</h2>
  <div class="field"><span class="label">Model ID:</span><span class="value">{{ record.model_id }}</span></div>
  {% if record.parent_id %}<div class="field"><span class="label">Parent Model:</span><span class="value">{{ record.parent_id }}</span></div>{% endif %}
  <div class="field"><span class="label">Timestamp:</span><span class="value">{{ record.timestamp }}</span></div>
</div>

<div class="section">
  <h2>Provenance</h2>
  {% if record.trainer %}<div class="field"><span class="label">Trainer:</span><span class="value">{{ record.trainer }}</span></div>{% endif %}
  {% if record.training_data %}<div class="field"><span class="label">Training Data:</span><span class="value">{{ record.training_data }}</span></div>{% endif %}
  {% if record.deployer %}<div class="field"><span class="label">Deployer:</span><span class="value">{{ record.deployer }}</span></div>{% endif %}
  {% if record.training_params %}
  <div class="field"><span class="label">Training Parameters:</span></div>
  {% for k, v in record.training_params.to_dict().items() %}
  <div class="field"><span class="label" style="padding-left:20px">{{ k }}:</span><span class="value">{{ v }}</span></div>
  {% endfor %}
  {% endif %}
</div>

{% if record.evaluations %}
<div class="section">
  <h2>Evaluations</h2>
  {% for ev in record.evaluations %}
  <div class="field"><span class="label">{{ ev.name }}:</span><span class="value">{{ ev.result }}</span></div>
  {% endfor %}
</div>
{% endif %}

<div class="section">
  <h2>Cryptographic Integrity</h2>
  <div class="field"><span class="label">Record Hash:</span><span class="value hash">{{ record.record_hash }}</span></div>
  {% if record.parent_hash %}<div class="field"><span class="label">Parent Hash:</span><span class="value hash">{{ record.parent_hash }}</span></div>{% endif %}
  <div class="field"><span class="label">Signature:</span><span class="value hash">{{ record.signature[:64] }}...</span></div>
  <div class="field"><span class="label">Chain Verified:</span><span class="value {{ 'verified' if verified else 'unverified' }}">{{ '✅ VERIFIED' if verified else '❌ UNVERIFIED' }}</span></div>
</div>

{% if lineage and lineage|length > 1 %}
<div class="section">
  <h2>Lineage Chain</h2>
  <div class="chain">
    {% for ancestor in lineage %}
    <div class="chain-item">
      <strong>{{ ancestor.model_id }}</strong>
      {% if ancestor.trainer %} — trained by {{ ancestor.trainer }}{% endif %}
      <br><span class="hash">{{ ancestor.record_hash }}</span>
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}

<footer>
  Generated by AI Model Provenance Tracker v0.1.0 on {{ generated_at }}
</footer>
</body>
</html>"""


def generate_certificate(
    record: ProvenanceRecord,
    lineage: List[ProvenanceRecord],
    verified: bool,
    output_path: Path,
    fmt: str = "html",
):
    template = Template(HTML_TEMPLATE)
    html = template.render(
        record=record,
        lineage=lineage,
        verified=verified,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
    )

    if fmt == "html":
        output_path.write_text(html)
    elif fmt == "pdf":
        try:
            from weasyprint import HTML as WeasyHTML
            WeasyHTML(string=html).write_pdf(str(output_path))
        except ImportError:
            raise RuntimeError("PDF export requires weasyprint. Install with: pip install 'ai-model-provenance-tracker[pdf]'")

    return output_path
